[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
time = "0.2.23"
sea-schema = { version = "0.14.0", default-features = false, features = [ "debug-print"] }
sea-orm-migration = "0.12.2"
sea-query = { version = "0.28.5", features = ["uuid", "bigdecimal", "with-bigdecimal", "with-chrono", "with-json", "backend-postgres", "sea-query-derive", "backend-postgres", "derive", "with-uuid", "thread-safe"] }
bot_impl = { path = "../bot_impl" }
botapi = { path = "../bot_impl/botapi-rs" }
tggen = { path = "../bot_impl/botapi-rs/generate" }
async-trait = "0.1.73"
openssl = { version = "0.10.56", features=["vendored"]}
tokio = { version = "1.32.0", features = ["net", "socket2", "io-util", "tokio-macros"] }
rustls-webpki = "0.101.4"

