[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-schema = { version = "0.11.0", default-features = false, features = [ "debug-print"] }
sea-orm-migration = "0.11.1"
sea-query = { version = "0.28.3", features = ["uuid", "bigdecimal", "with-bigdecimal", "with-chrono", "with-json", "backend-postgres", "sea-query-derive", "backend-postgres", "derive", "with-uuid", "thread-safe"] }
bobot_impl = { path = "../bobot_impl" }
botapi = { path = "../bobot_impl/botapi-rs" }
tggen = { path = "../bobot_impl/botapi-rs/generate" }
async-trait = "0.1.66"
openssl = { version = "0.10.45" }
tokio = { version = "1.26.0", features = ["net", "socket2", "io-util", "tokio-macros"] }
