[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
time = "0.3.29"
sea-schema = { version = "0.14.1", default-features = false, features = [ "debug-print"] }
sea-orm-migration = "0.12.3"
sea-query = { version = "0.30.2", features = ["uuid", "bigdecimal", "with-bigdecimal", "with-chrono", "with-json", "backend-postgres", "sea-query-derive", "backend-postgres", "derive", "with-uuid", "thread-safe"] }
bot_impl = { path = "../bot_impl" }
botapi = { path = "../bot_impl/botapi-rs" }
tggen = { path = "../bot_impl/botapi-rs/generate" }
async-trait = "0.1.73"
openssl = { version = "0.10.57", features=["vendored"]}
tokio = { version = "1.32.0", features = ["net", "socket2", "io-util", "tokio-macros"] }
rustls-webpki = "0.101.6"
chrono = "0.4.31"

