[package]
name = "bobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.27.0", features = ["full", "net", "socket2", "io-util", "tokio-macros"] }
migration = { path = "migration" }
bobot_impl = { path = "bobot_impl" }
openssl = { version = "0.10.49", features = ["vendored"] }
clap = { version = "4.2.1", features = ["derive"] }
markdown = "0.3.0"
