[package]
name = "dijkstra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.28.2", features = ["full", "net", "socket2", "io-util", "tokio-macros"] }
migration = { path = "migration" }
bot_impl = { path = "bot_impl" }
openssl = { version = "0.10.55", features = ["vendored"] }
clap = { version = "4.3.5", features = ["derive"] }
markdown = "0.3.0"
