[package]
name = "dijkstra"
version = "0.4.12"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.36"
futures = "0.3.30"
lazy_static = "1.4.0"
log = "0.4.21"
redis = { version = "0.25", features = [
    "acl",
    "aio",
    "r2d2",
    "geospatial",
    "script",
    "tokio-comp",
    "cluster",
] }
rmp-serde = "1.3.0"
sea-orm = { version = "0.12.15", features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "macros",
    "default",
    "debug-print",
    "mock",
    "tests-cfg",
] }
sea-query = { version = "0.30.7", features = [
    "uuid",
    "bigdecimal",
    "with-bigdecimal",
    "with-chrono",
    "with-json",
    "backend-postgres",
    "sea-query-derive",
    "derive",
    "with-uuid",
    "thread-safe",
    "postgres-types",
    "with-time",
] }
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full", "rt"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
async-trait = "0.1.80"
async_nursery = "0.5.0"
bb8 = "0.8.5"
bb8-redis = "0.15.0"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.7", features = ["derive"] }
serde_json = "1.0.117"
pomelo = "0.1.5"
regex = "1.10.5"
higher-order-closure = "0.0.5"
botapi = { path = "botapi-rs", features = ["rhai"] }
confy = "0.6.1"
sea-orm-migration = "0.12.15"
nonblock-logger = { version = "0.2.2", features = ["color"] }
dashmap = "5.5.3"
once_cell = "1.19.0"
openssl = { version = "0.10.64", features = ["vendored"] }
prometheus = "0.13.4"
warp = "0.3.7"
prometheus-hyper = "0.2.0"
markdown = "0.3.0"
itertools = "0.13.0"
macros = { path = "macros" }
hyper = "1.3.1"
strum = "0.26.2"
humantime = "2.1.0"
captcha = "0.0.9"
rand = "0.8.5"
base64 = "0.22.1"
glob-match = "0.2.1"
globset = { version = "0.4.14", features = ["serde"] }
wildmatch = "2.3.4"
glob = "0.3.1"
rhai = { version = "1.18.0", features = [
    "serde",
    "sync",
    "metadata",
    "internals",
] }
#llama-rs = { path = "./llama-rs/llama-rs" }
rusty_pool = "0.7.0"
seq-macro = "0.3.5"
convert_case = "0.6.0"
unicase = "2.7.0"
unicase_serde = "0.1.0"
yoke = { version = "0.7.4", features = ["derive", "serde"] }
governor = "0.6.3"
rustls-webpki = "0.102.4"
reqwest = "0.12.5"
bytes = { version = "1.6.0", features = ["serde"] }
lz4_flex = "0.11.3"
sqlx = "0.7.4"
redis-test = { version = "0.4.0", features = ["aio"] }
threadpool = "1.8.1"
num_cpus = "1.16.0"

[build-dependencies]
anyhow = "1.0.86"

[workspace]
members = ['migration']
