services:
  bobot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config:Z
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bobot
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=bobot
    volumes: 
      - bobot-db:/var/lib/postgresql/data 
  redis:
    image: redis:7.0.7-alpine
    restart: always
    volumes: 
      - bobot-redis:/data  
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
       
volumes:
  bobot-redis:
  bobot-db: