services:
  bobot:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: docker.io/gnu3ra/dijkstra:latest
    pull_policy: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config:z
    depends_on:
      migrate:
        condition: service_completed_successfully
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    image: docker.io/gnu3ra/dijkstra_migrate:latest
    pull_policy: always
    environment:
      - POSTGRES_USER=bobot
      - POSTGRES_PASSWORD_FILE=/run/secrets/pass
      - POSTGRES_DB=bobot
    secrets:
      - pass
    depends_on:
      db:
        condition: service_healthy
  db:
    image: docker.io/postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bobot
      - POSTGRES_PASSWORD_FILE=/run/secrets/pass
      - POSTGRES_DB=bobot
    secrets:
      - pass
    volumes: 
      - bobot-db:/var/lib/postgresql/data 
    healthcheck:
      test: pg_isready -U bobot
      interval: 10s
      timeout: 3s
      retries: 10
  redis:
    image: docker.io/redis:7.0.7-alpine
    restart: always
    volumes: 
      - bobot-redis:/data  
  prometheus:
    image: docker.io/prom/prometheus:v2.41.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus:z
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
       
volumes:
  bobot-redis:
  bobot-db:
  prometheus-data:
  cargo-cache:
  migration-target:

secrets:
  pass:
    file: db_pass.txt