[package]
name = "bobot_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.14"
redis = { version = "0.21.5", features = ["acl", "aio", "r2d2", "geospatial", "script", "tokio-comp", "cluster"] }
rmp-serde = "1.0.0"
sea-orm = { version = "0.6.0", features = ["runtime-tokio-rustls", "sqlx-postgres", "macros", "default"] }
sea-query = { version = "0.22.0", features = ["uuid", "bigdecimal", "with-bigdecimal", "with-chrono", "with-json", "postgres", "sea-query-derive", "backend-postgres", "derive", "postgres-array", "with-uuid", "thread-safe"] }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
anyhow = "1.0.55"
async-trait = "0.1.52"
async_executors = { version = "0.5.1", features = ["tokio_io", "tokio_tp", "tokio", "tokio_timer"] }
async_nursery = "0.4.0"
bb8 = "0.7.1"
bb8-redis = "0.10.1"
chrono = { version = "0.4.19", features = ["serde"] }
dashmap = "5.1.0"
grammers-client = { git = "https://github.com/Lonami/grammers.git" }
grammers-session = { git = "https://github.com/Lonami/grammers.git" }
grammers-mtproto = { git = "https://github.com/Lonami/grammers.git" }
grammers-mtsender = { git = "https://github.com/Lonami/grammers.git" }
sea-schema = { version = "0.5.0", default-features = false, features = [ "migration", "debug-print" ] }
macros = { path = "../macros" }
clap = { version = "3.1.6", features = ["derive"] }
serde_json = "1.0"
pomelo = "0.1.5"
regex = "1"
flexi_logger = { version = "0.22", features = [ "async", "colors" ] }
higher-order-closure = "0.0.5"
botapi = { path = "./botapi-rs" }
