[package]
name = "buildhelpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.106"
quote = "1.0.22"
proc-macro2 = "1.0.60"
glob = "0.3.0"
